apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    name: webapp
    ports:
    - containerPort: 8080
    envFrom:
    - secretRef:
        name: db-secret
